# -*- coding: utf-8 -*-
"""D8(01).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqD9Rq26mzOoAIWSUvK6BOoQwIgPpVJP

TasksArray Creation             
Create a 1D array of numbers from 10 to 50.              
Create a 3x3 array of random numbers between 0 and 1.           
Array Attributes             
Find the shape, size, and data type of the array you created in the previous task.             
Basic Operations             
Add 5 to every element of a 1D array.                
Multiply two 2D arrays element-wise.              
Indexing and Slicing             
Create a 5x5 array of integers from 1 to 25. Extract:              
The first row.               
The last column.              
A subarray of the first three rows and first two columns.             
Aggregation             
Create a 10-element array of random integers between 10 and 100. Find:      
The maximum value.          
The minimum value.           
The mean and standard deviation.         
Reshaping        
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.         
Broadcasting              
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.        
Filtering         
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.            
Matrix Multiplication            
Create two 2x2 matrices and perform matrix multiplication.             
Advanced Indexing           
Given a 4x4 array, use fancy indexing to extract the diagonal elements.
"""

import numpy as np
Arr=np.arange(10,50)
print(Arr)
print()
Arr1=np.random.rand(3,3)
print(Arr1)
print()

#1
print("Array attributes:")
print("Size of array 1: ",np.size(Arr))
print("Size of array 2: ",np.size(Arr1))
print("Shape of array 1: ",np.shape(Arr))
print("Shape of array 2: ",np.shape(Arr1))
print("Data type of array 1: ",Arr.dtype)
print("Data type of array 2: ",Arr1.dtype)

#2
print("Basic Operations")
Arr=Arr+5
print("Added 5 to every element: ",Arr)
Arr2=np.random.rand(3,3)
print("Multiplication of two arrays:\n ",Arr1*Arr2)

#3
Arr3=np.arange(1,26)
Arr3=Arr3.reshape(5,5)
print(Arr3)
print("First row: ",Arr3[0])
print("Last column: ",Arr3[:,-1])
print("Subarray: \n",Arr3[:3,:2])

#4
Arr4=np.random.randint(10,100,10)
print(Arr4)
print("Maximum value: ",np.max(Arr4))
print("Minimum value: ",np.min(Arr4))
print("Mean: ",np.mean(Arr4))
print("Standard deviation: ",np.std(Arr4))

#6
Arr5=np.arange(1,13)
Arr5=Arr5.reshape(3,4)
print(Arr5)

#7
Arr6=np.ones((3,3))
print(Arr6)
Arr6=Arr6+np.array([1,2,3])
print(Arr6)

#8
Arr7=np.random.randint(1,50,50)
print(Arr7)
Arr7=Arr7[Arr7%5==0]
print(Arr7)

#9
Arr8=np.random.rand(2,2)
Arr9=np.random.rand(2,2)
print(Arr8)
print(Arr9)
print(np.matmul(Arr8,Arr9))

#10
Arr10=np.random.randint(1,100,4)
print(Arr10)
print(np.diag(Arr10))

