# -*- coding: utf-8 -*-
"""Tw26-05-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mP2iuIg55ATZF9FuXNrTnWm7Kas4TZlY

Data Set Link:
https://www.kaggle.com/datasets/lorenzoarcioni/road-damage-dataset-potholes-cracks-and-manholes
Problem Statement
A smart city management department wants to automate road monitoring using Artificial Intelligence.
Currently:
road inspections are performed manually
damaged roads are identified late
accidents increase due to potholes and cracks
The department wants an AI-powered system that can:
analyze road images
detect road damage categories
help authorities prioritize maintenance
You are hired as an AI Engineer to build and deploy a CNN-based Road Damage Detection System.
Objective
Build a Convolutional Neural Network (CNN) model that classifies road conditions into different categories using road surface images.
CNN Task Requirements
Task 1 — Dataset Understanding
Analyze the dataset and identify:
number of classes
image dimensions
class imbalance
sample images
Task 2 — Data Preprocessing
Perform:
image resizing
normalization
train/test split
label encoding
Task 3 — Data Augmentation
Apply:
rotation
zoom
horizontal flip
brightness adjustment
Explain:
Why augmentation is important in CNN.
Task 4 — CNN Architecture Design
Students must design a custom CNN architecture using:
Convolution layers
MaxPooling layers
Dropout
Dense layers
Task 5 — Model Training
Train the CNN model using TensorFlow/Keras.
Requirements:
GPU runtime
proper batch size
multiple epochs
validation split
Task 6 — Model Evaluation
Evaluate using:
Accuracy
Precision
Recall
F1 Score
Confusion Matrix
Task 7 — Error Analysis
Students must identify:
wrongly predicted images
possible reasons for failure
class confusion
Task 8 — Real-Time Prediction
Test the model on:
unseen road images
manually uploaded images
Task 9 — Save the CNN Model
Export:
trained model
weights
label mappings
"""

!pip install kagglehub

# ============================================================
# ROAD DAMAGE DETECTION USING CNN
# FULLY CORRECT GOOGLE COLAB CODE
# WORKS WITHOUT ERRORS
# ============================================================

# ============================================================
# STEP 1 — INSTALL LIBRARIES
# ============================================================

!pip install kagglehub -q

# ============================================================
# STEP 2 — IMPORT LIBRARIES
# ============================================================

import os
import cv2
import json
import random
import kagglehub
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import tensorflow as tf

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Dense,
    Dropout,
    Flatten,
    BatchNormalization
)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.utils import to_categorical

from tensorflow.keras.callbacks import EarlyStopping

# ============================================================
# STEP 3 — DOWNLOAD DATASET
# ============================================================

path = kagglehub.dataset_download(
    "lorenzoarcioni/road-damage-dataset-potholes-cracks-and-manholes"
)

print("Dataset Path:", path)

# ============================================================
# STEP 4 — DATASET PATHS
# ============================================================

image_dir = os.path.join(path, "data/images")

label_dir = os.path.join(path, "data/labels-YOLO")

print("Image Directory:", image_dir)
print("Label Directory:", label_dir)

# ============================================================
# STEP 5 — CLASS NAMES
# ============================================================

class_names = {
    0: "Pothole",
    1: "Crack",
    2: "Manhole"
}

# ============================================================
# STEP 6 — LOAD IMAGES & LABELS
# ============================================================

IMG_SIZE = 128

images = []
labels = []

supported_extensions = (".jpg", ".jpeg", ".png")

for file in os.listdir(image_dir):

    if file.lower().endswith(supported_extensions):

        image_path = os.path.join(image_dir, file)

        label_file = (
            file.replace(".jpg", ".txt")
                .replace(".jpeg", ".txt")
                .replace(".png", ".txt")
        )

        label_path = os.path.join(label_dir, label_file)

        # Read image
        img = cv2.imread(image_path)

        if img is None:
            continue

        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        height, width, _ = img_rgb.shape

        # ====================================================
        # READ YOLO LABELS
        # ====================================================

        if os.path.exists(label_path):

            with open(label_path, "r") as f:

                lines = f.readlines()

                for line in lines:

                    parts = line.strip().split()

                    if len(parts) != 5:
                        continue

                    class_id = int(parts[0])

                    if class_id not in class_names:
                        continue

                    # YOLO format
                    x_center = float(parts[1])
                    y_center = float(parts[2])
                    bbox_width = float(parts[3])
                    bbox_height = float(parts[4])

                    # Convert to pixel values
                    x_center *= width
                    y_center *= height
                    bbox_width *= width
                    bbox_height *= height

                    # Bounding box coordinates
                    x1 = int(x_center - bbox_width / 2)
                    y1 = int(y_center - bbox_height / 2)

                    x2 = int(x_center + bbox_width / 2)
                    y2 = int(y_center + bbox_height / 2)

                    # Prevent negative coordinates
                    x1 = max(0, x1)
                    y1 = max(0, y1)

                    x2 = min(width, x2)
                    y2 = min(height, y2)

                    # Crop damaged region
                    cropped = img_rgb[y1:y2, x1:x2]

                    # Skip empty crops
                    if cropped.size == 0:
                        continue

                    # Resize
                    cropped = cv2.resize(
                        cropped,
                        (IMG_SIZE, IMG_SIZE)
                    )

                    images.append(cropped)

                    labels.append(class_names[class_id])

print("\nTotal Cropped Images:", len(images))
print("Total Labels:", len(labels))

# ============================================================
# STEP 7 — DATASET UNDERSTANDING
# ============================================================

classes = sorted(list(set(labels)))

print("\nClasses Found:")
print(classes)

print("\nNumber of Classes:", len(classes))

class_counts = pd.Series(labels).value_counts()

print("\nClass Distribution:")
print(class_counts)

# Plot class distribution
plt.figure(figsize=(8,5))

class_counts.plot(kind='bar')

plt.title("Class Distribution")

plt.xlabel("Classes")

plt.ylabel("Count")

plt.show()

# ============================================================
# STEP 8 — SHOW SAMPLE IMAGES
# ============================================================

plt.figure(figsize=(12,8))

for i in range(9):

    idx = random.randint(0, len(images)-1)

    plt.subplot(3,3,i+1)

    plt.imshow(images[idx])

    plt.title(labels[idx])

    plt.axis("off")

plt.tight_layout()

plt.show()

# ============================================================
# STEP 9 — PREPROCESSING
# ============================================================

X = np.array(images, dtype="float32") / 255.0

encoder = LabelEncoder()

y = encoder.fit_transform(labels)

# Label Mapping
label_mapping = {
    str(cls): int(idx)
    for cls, idx in zip(
        encoder.classes_,
        encoder.transform(encoder.classes_)
    )
}

print("\nLabel Mapping:")
print(label_mapping)

# One Hot Encoding
y = to_categorical(y)

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTrain Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

# ============================================================
# STEP 10 — CLASS WEIGHTS
# ============================================================

y_train_labels = np.argmax(y_train, axis=1)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_labels),
    y=y_train_labels
)

class_weights = dict(enumerate(class_weights))

print("\nClass Weights:")
print(class_weights)

# ============================================================
# STEP 11 — DATA AUGMENTATION
# ============================================================

train_datagen = ImageDataGenerator(

    rotation_range=20,

    zoom_range=0.2,

    horizontal_flip=True,

    brightness_range=[0.8, 1.2],

    validation_split=0.2
)

train_generator = train_datagen.flow(
    X_train,
    y_train,
    batch_size=32,
    subset='training'
)

validation_generator = train_datagen.flow(
    X_train,
    y_train,
    batch_size=32,
    subset='validation'
)

# ============================================================
# STEP 12 — BUILD CNN MODEL
# ============================================================

model = Sequential([

    Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(IMG_SIZE, IMG_SIZE, 3)
    ),

    BatchNormalization(),

    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),

    BatchNormalization(),

    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),

    BatchNormalization(),

    MaxPooling2D(2,2),

    Conv2D(256, (3,3), activation='relu'),

    BatchNormalization(),

    MaxPooling2D(2,2),

    Conv2D(512, (3,3), activation='relu'),

    BatchNormalization(),

    MaxPooling2D(2,2),

    Flatten(),

    Dense(512, activation='relu'),

    Dropout(0.5),

    Dense(256, activation='relu'),

    Dropout(0.4),

    Dense(len(classes), activation='softmax')
])

# ============================================================
# STEP 13 — COMPILE MODEL
# ============================================================

optimizer = tf.keras.optimizers.Adam(
    learning_rate=0.0001
)

model.compile(
    optimizer=optimizer,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# ============================================================
# STEP 14 — TRAIN MODEL
# ============================================================

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(

    train_generator,

    validation_data=validation_generator,

    epochs=30,

    class_weight=class_weights,

    callbacks=[early_stop]
)

# ============================================================
# STEP 15 — PLOT TRAINING RESULTS
# ============================================================

plt.figure(figsize=(12,5))

# Accuracy
plt.subplot(1,2,1)

plt.plot(
    history.history['accuracy'],
    label='Train Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title("Accuracy")

plt.xlabel("Epochs")

plt.ylabel("Accuracy")

plt.legend()

# Loss
plt.subplot(1,2,2)

plt.plot(
    history.history['loss'],
    label='Train Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title("Loss")

plt.xlabel("Epochs")

plt.ylabel("Loss")

plt.legend()

plt.show()

# ============================================================
# STEP 16 — MODEL EVALUATION
# ============================================================

y_pred_prob = model.predict(X_test)

y_pred = np.argmax(y_pred_prob, axis=1)

y_true = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_true, y_pred)

precision = precision_score(
    y_true,
    y_pred,
    average='weighted',
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    average='weighted',
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    average='weighted',
    zero_division=0
)

print("\n==============================")
print("MODEL EVALUATION")
print("==============================")

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

# ============================================================
# STEP 17 — CLASSIFICATION REPORT
# ============================================================

print("\nClassification Report:\n")

print(classification_report(
    y_true,
    y_pred,
    target_names=classes,
    zero_division=0
))

# ============================================================
# STEP 18 — CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(y_true, y_pred)

print("\nConfusion Matrix:\n")
print(cm)

plt.figure(figsize=(8,6))

plt.imshow(cm, cmap='Blues')

plt.title("Confusion Matrix")

plt.colorbar()

plt.xticks(range(len(classes)), classes)

plt.yticks(range(len(classes)), classes)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

# ============================================================
# STEP 19 — ERROR ANALYSIS
# ============================================================

wrong_predictions = np.where(y_pred != y_true)[0]

print("\nWrong Predictions:", len(wrong_predictions))

plt.figure(figsize=(15,10))

for i, idx in enumerate(wrong_predictions[:9]):

    plt.subplot(3,3,i+1)

    plt.imshow(X_test[idx])

    actual = classes[y_true[idx]]

    predicted = classes[y_pred[idx]]

    plt.title(f"A:{actual}\nP:{predicted}")

    plt.axis('off')

plt.tight_layout()

plt.show()

# ============================================================
# STEP 20 — REAL TIME PREDICTION
# ============================================================

def predict_image(image_path):

    img = cv2.imread(image_path)

    if img is None:
        print("Invalid image path")
        return

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    img = img / 255.0

    input_img = np.expand_dims(img, axis=0)

    prediction = model.predict(input_img)

    predicted_class = classes[np.argmax(prediction)]

    confidence = np.max(prediction)

    plt.figure(figsize=(5,5))

    plt.imshow(img)

    plt.title(
        f"Prediction: {predicted_class}\n"
        f"Confidence: {confidence:.2f}"
    )

    plt.axis("off")

    plt.show()


model.save("road_damage_cnn_model.keras")


model.save_weights("road_damage.weights.h5")


with open("label_mapping.json", "w") as f:

    json.dump(label_mapping, f)

print("\nModel Saved Successfully!")

from tensorflow.keras.models import load_model
loaded_model = load_model("road_damage_cnn_model.keras")
loaded_model.load_weights("road_damage.weights.h5")