# -*- coding: utf-8 -*-
"""D9(02).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgSLjrQDwDJOoWwxclazpOmtgpp_zDRi
"""

pip install pandas

import pandas as pd
import numpy as np
a=[1,2,3,4,5]
b=pd.Series(a)
print(b)

ad={'1st':1,'2nd':3,'3rd':5}
ser=pd.Series(ad)
print(ser)

"""Your Task-1:

Using **Pandas Series**, perform the following:

✅ Create a Series named `scores` using the dictionary `student_scores`.

✅ Print the marks scored by **"Charlie"** and **"Eva"**.

✅ Add **5 bonus marks** to all students and print the updated Series.

✅ Display only the students who scored **above 90** after the bonus.

✅ Calculate and print the **average marks** of the class (after the bonus).

"""

import pandas as pd
import numpy as np
student_scores={'Neha': 90,
     'Sree':87,
     'Siddi':95,
     'Charlie':86,
     'Niha':89,
     'Eva':85,
     'Tarun':80,
     'Varun':92}
scores=pd.Series(student_scores)
print(scores)
print("Charlie score: ",scores['Charlie'])
print("Eva score: ",scores['Eva'])
scores=scores+5
print("Updated Scores:\n",scores)
print("Scores >90:\n",scores[scores>90])
print("Average Score: ",scores.mean())

anarray=np.array([[25,85],[25,90],[26,70],[24,80]])
ser=pd.DataFrame(anarray,index=['Neha','Sree','Siddi','Niha'],columns=['Age','Marks'])
print(ser)

print(ser.values)
print(ser.index)
print(ser.columns)

import pandas as pd
adict={'name':{'N':'Neha','S':'Siddi','V':'Varun','T':'Tarun'},
       'age':{'N':19,'S':23,'V':21,'T':25},
       'marks':{'N':90,'S':87,'V':92,'T':80}}
df=pd.DataFrame(adict)
df

a_dict={'name':['Rukesh','Prasad','Gian','Hansana'],
        'age':[25,25,26,24],
        'marks':[85,90,70,80]}
df=pd.DataFrame(a_dict)
df

print(df.index)
print(df.age)
print(df.columns)
print(df.values)
print(type(df.values))
print(df.values.ndim)
print(df.values.shape)

import pandas as pd

ser1 = pd.Series(['Rukshan', 'Prasadi', 'Gihan', 'Hansana'], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser2 = pd.Series([25, 25, 26, 24], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser3 = pd.Series([85, 90, 70, 80], index=['Ru', 'Pr', 'Gi', 'Ha'])

a_dict = {'name': ser1, 'age': ser2, 'marks': ser3}

df = pd.DataFrame(a_dict)
df

"""Task-2
You are given three Series representing student data:

Names of students

Their ages

Their marks

These series are combined into a DataFrame as shown earlier.

### 🎯 Your Task:
Using the existing DataFrame, perform the following operations:

✅ Print the details (name, age, marks) of the student who scored the highest marks.

✅ Add a new student "Tharushi" with age 23 and marks 88 using the index "Th".

✅ Display the details of students who are 25 years old or older.

✅ Increase the marks of students below 80 by 10 bonus points.

✅ Calculate and print the average marks of all students after the bonus.

"""

import pandas as pd
import numpy as np
student_names = pd.Series(['Neha','Siddi','Varun','Tarun'],index=['N','S','V','T'])
student_ages = pd.Series([19,23,21,25],index=['N','S','V','T'])
student_marks = pd.Series([90,87,92,80],index=['N','S','V','T'])
student_data = pd.DataFrame({'Name':student_names,'Age':student_ages,'Marks':student_marks})
student_data

print(" Student with highest marks:\n",student_data.loc[student_data['Marks'].idxmax()])
student_data.loc['Th'] = ['Tharushi', 23, 88]
print(student_data)
print(" Students aged 25 or older:",student_data[student_data['Age'] >= 25])
student_data.loc[student_data['Marks'] < 80, 'Marks'] += 10
print(" After adding 10 bonus marks to students with marks < 80:")
print(student_data)
average_marks = student_data['Marks'].mean()
print(f" Average marks after bonus: {average_marks:.2f}")

"""Analysis the data"""

import pandas as pd
import numpy as np
data=pd.read_csv('/data.csv')
df=pd.DataFrame(data)
df.head()

print(df.shape)
print(df.info())
print(df.tail())
print(df.describe())

df.isnull()

df.isnull().sum()

df1=df.dropna()

print(df1.to_string())

x=df["Calories"].median()
df.fillna({'Calories':x},inplace=True)
df.isnull().sum()

df['Date'] = pd.to_datetime(df['Date'], errors='coerce', infer_datetime_format=True)
print(df.to_string())

df.loc[7,'Duration']=45
print(df.to_string())

for x in df.index:
  if df.loc[x,"Duration"]>120:
    df.loc[x,"Duration"]=120

for x in df.index:
  if df.loc[x,"Duration"]>120:
    df.drop(x,inplace=True)
print(df)

high_pulse=df[df['Pulse']>110]
print(high_pulse)

sorted_df=df.sort_values(by='Calories',ascending=False)
print(sorted_df)

trainer_df = pd.DataFrame({
    'Date': ['2020/12/01', '2020/12/02', '2020/12/03'],
    'Trainer': ['Alex', 'Jordan', 'Taylor']
})

trainer_df['Date'] = pd.to_datetime(trainer_df['Date'])

merged_df = pd.merge(df, trainer_df, on='Date', how='left')

print(merged_df)

avg_calories_by_duration = df.groupby('Duration')['Calories'].mean()

df['PulseRange'] = pd.cut(df['Pulse'], bins=[100, 110, 120, 130, 140, 150, 180])
grouped_stats = df.groupby('PulseRange', observed=False).agg({
    'Calories': 'mean',
    'Maxpulse': 'max'
})

print(grouped_stats)

df.rename(columns={'Maxpulse':'Max_Pulse'},inplace=True)

df.query('Pulse>110 and Calories<400')
df[df['Calories'].between(200,500)]

